task: comsense
displayname: Common Sense Reasoning
description: |
  Common sense reasoning tasks are intended to require the model to go beyond pattern recognition.
  Instead, the model should use "common sense" or world knowledge to make inferences.
