task: nli
displayname: Natural Language Inference
description: |
  Natural language inference is the task of determining whether a "hypothesis" is
  true (entailment), false (contradiction), or undetermined (neutral) given a "premise".