name: Generate Dist

on:
  push:
    branches: [ master ]
    paths: [ 'adapters/**', 'architectures/**' ]

jobs:
  generate:
    if: github.repository_owner == 'Adapter-Hub'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install
        run: |
          pip install -r scripts/requirements.txt
      - name: Run generation
        run: |
          python scripts/generate.py
      - name: Commit
        run: |
          git config user.name "Adapter Hub Bert"
          git config user.email "65732326+adapter-hub-bert@users.noreply.github.com"
          git add dist
          if [[ `git status --porcelain` ]]; then
            git commit -m "Generate dist files."
            git remote set-url origin https://x-access-token:${{ secrets.BOT_TOKEN }}@github.com/${{ github.repository }}
            git push origin master
          fi
      - name: Trigger website build
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.BOT_TOKEN }}
          repository: Adapter-Hub/website
          event-type: build
